version: 0.2

phases:
  build:
    commands:
      - cd endtoendmlproject
      - zip -r ../deploy.zip . -x "venv/*" "__pycache__/*" "*.pyc" "logs/*"

artifacts:
  files:
    - deploy.zip
  discard-paths: yes
